# Generated by Django 5.2 on 2025-04-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="tg_chat_id"
            ),
        ),
    ]
