# Generated by Django 5.2 on 2025-04-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=30, verbose_name="место")),
                ("time_at", models.TimeField(verbose_name="время")),
                ("action", models.CharField(max_length=50, verbose_name="действие")),
                (
                    "pleasant_habit",
                    models.CharField(max_length=50, verbose_name="приятная привычка"),
                ),
                (
                    "period",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="периодичность (дни)"
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="вознаграждение",
                    ),
                ),
                (
                    "time_to_complete",
                    models.DurationField(verbose_name="время на выполнение"),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, verbose_name="публичная привычка"
                    ),
                ),
            ],
            options={
                "verbose_name": "привычка",
                "verbose_name_plural": "привычки",
            },
        ),
    ]
