# Generated by Django 5.2 on 2025-04-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habits_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habits",
            name="pleasant_habit",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="приятная привычка"
            ),
        ),
    ]
