# Generated by Django 5.2 on 2025-04-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_alter_habits_pleasant_habit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habits",
            name="pleasant_habit",
            field=models.BooleanField(
                default=False, verbose_name="это приятная привычка"
            ),
        ),
    ]
